services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back
    env_file:
      - ./dockerproperties.env
  
  java:
    build:
      context: ./javabackend
      dockerfile: Dockerfile
    container_name: javabackend
    ports:
      - "8080:8080"
    networks:
      - back
    env_file:
      - ./dockerproperties.env

  kotlin:
    build:
      context: ./kotlinbackend
      dockerfile: Dockerfile
    container_name: kotlinbackend
    ports:
      - "8081:8081"
    networks:
      - back
    env_file:
      - ./dockerproperties.env

volumes:
  db_data:

networks:
  back: